"""Champion identity + local catalogue.

The catalogue is loaded from a bundled JSON asset (generated by
scripts/build_champion_catalog.py against Riot Data Dragon). At runtime the LCU
/live-data endpoint is preferred when connected; this bundle guarantees Nexus
works offline, in simulation mode, and in tests without any network.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Optional

def _find_asset_catalog() -> Path:
    """Locate assets/champions.json whether running from a checkout or installed."""
    here = Path(__file__).resolve()
    for base in (here.parents[4], here.parents[3], here.parents[2]):
        cand = base / "assets" / "champions.json"
        if cand.exists():
            return cand
    return here.parents[2] / "assets" / "champions.json"


ASSET_CATALOG = _find_asset_catalog()


@dataclass(frozen=True)
class Champion:
    id: int
    key: str            # numeric champion key used by DDragon image URLs
    name: str           # display name, e.g. "Kai'Sa"
    alias: str          # e.g. "TheVirtualArcanist"
    roles: tuple[str, ...]
    resource: str = "mana"

    @property
    def square_icon_url(self) -> str:
        return f"https://ddragon.leagueoflegends.com/cdn/img/champion/square/{self.alias}_0.jpg"

    @property
    def loading_url(self) -> str:
        return f"https://ddragon.leagueoflegends.com/cdn/img/champion/loading/{self.alias}_0.jpg"

    def matches(self, needle: str) -> bool:
        n = needle.casefold()
        return n in self.name.casefold() or n in self.key or n in self.alias.casefold()


def _normalise_alias(name: str) -> str:
    """DDragon aliases strip apostrophes/periods: Kai'Sa -> KaiSa, Kog'Maw -> KogMaw."""
    return re.sub(r"[^A-Za-z0-9]", "", name)


class ChampionCatalog:
    def __init__(self, champions: list[Champion]) -> None:
        self._by_id = {c.id: c for c in champions}
        self._by_key = {c.key: c for c in champions}
        self._by_name = {c.name.casefold(): c for c in champions}
        self._all = sorted(champions, key=lambda c: c.name.casefold())

    @classmethod
    def load(cls, path: Optional[Path] = None) -> "ChampionCatalog":
        p = path or ASSET_CATALOG
        with p.open("r", encoding="utf-8") as fh:
            raw = json.load(fh)
        champs = [Champion(id=int(c["id"]), key=str(c["key"]), name=c["name"],
                           alias=c.get("alias") or _normalise_alias(c["name"]),
                           roles=tuple(c.get("roles", [])),
                           resource=c.get("resource", "mana"))
                  for c in raw["champions"]]
        return cls(champs)

    def dump(self, path: Path) -> None:
        payload = {"version": 1,
                   "champions": [{"id": c.id, "key": c.key, "name": c.name,
                                  "alias": c.alias, "roles": list(c.roles),
                                  "resource": c.resource} for c in self._all]}
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=1), encoding="utf-8")

    # ------------------------------------------------------------- queries
    @property
    def all(self) -> list[Champion]:
        return list(self._all)

    def __len__(self) -> int:
        return len(self._all)

    def by_id(self, cid: int) -> Optional[Champion]:
        return self._by_id.get(int(cid))

    def by_key(self, key: str) -> Optional[Champion]:
        return self._by_key.get(str(key))

    def by_name(self, name: str) -> Optional[Champion]:
        return self._by_name.get(name.casefold())

    def search(self, needle: str) -> list[Champion]:
        if not needle.strip():
            return self.all
        return [c for c in self._all if c.matches(needle)]

    def for_role(self, role: str) -> list[Champion]:
        r = role.upper()
        return [c for c in self._all if r in {x.upper() for x in c.roles}]


@lru_cache(maxsize=1)
def default_catalog() -> ChampionCatalog:
    return ChampionCatalog.load()
