"""Design tokens — the single source of truth for visual values (spec §24).

Tokens are plain Python constants; `theme/tokens_qss.py` compiles them into
Qt palettes + QSS. Nothing in the UI may hard-code a colour/spacing value that
has a token equivalent.
"""
from __future__ import annotations

from dataclasses import dataclass


# ---------------------------------------------------------------- spacing
SP_0 = 0
SP_1 = 4
SP_2 = 8
SP_3 = 12
SP_4 = 16
SP_5 = 24
SP_6 = 32
SP_7 = 48
SPACING_SCALE = (SP_1, SP_2, SP_3, SP_4, SP_5, SP_6)   # 4/8/12/16/24/32


# ------------------------------------------------------------- typography
@dataclass(frozen=True)
class Typography:
    family_ui: str = "Segoe UI"
    family_fallbacks: tuple[str, ...] = ("Inter", "Noto Sans", "sans-serif")
    size_caption: int = 11
    size_body: int = 13
    size_control: int = 13
    size_subhead: int = 15
    size_headline: int = 20
    size_display: int = 28
    size_timer: int = 34
    weight_regular: int = 400
    weight_semibold: int = 600
    weight_bold: int = 700


TYPOGRAPHY = Typography()


def font_stack() -> str:
    return ", ".join((TYPOGRAPHY.family_ui,) + TYPOGRAPHY.family_fallbacks)


# ------------------------------------------------------------------ colours
@dataclass(frozen=True)
class Palette:
    # base surfaces (dark theme is primary)
    bg_root: str = "#0B0E13"          # app background
    bg_surface: str = "#12161D"       # cards / panels
    bg_raised: str = "#171C25"        # elevated controls
    bg_input: str = "#0E1218"
    bg_overlay: str = "#0B0E13"       # modals/toasts (with alpha applied)

    # borders & dividers
    border_subtle: str = "#222A35"
    border_strong: str = "#2E3947"
    divider: str = "#1A212B"

    # text
    text_primary: str = "#E8EDF4"
    text_secondary: str = "#9AA7B8"
    text_muted: str = "#5F6C7D"
    text_inverse: str = "#0B0E13"

    # accents (restrained: gold is the brand, blue is informational)
    accent_gold: str = "#C89B3C"
    accent_gold_soft: str = "#8A6B2A"
    accent_blue: str = "#0AC8B9"      # hextech teal for interactive highlight
    accent_hover: str = "#1FD8C8"

    # semantic
    ok: str = "#3DD68C"
    info: str = "#0AC8B9"
    warn: str = "#E8B23A"
    error: str = "#F0524F"
    danger: str = "#FF4B47"           # emergency stop only
    disabled_fg: str = "#4A5563"
    disabled_bg: str = "#141922"

    # state dot colours (paired with glyphs so meaning never relies on hue alone)
    dot_connected: str = "#3DD68C"
    dot_searching: str = "#0AC8B9"
    dot_champ_select: str = "#C89B3C"
    dot_disconnected: str = "#F0524F"
    dot_stale: str = "#E8B23A"


PALETTE_DARK = Palette()


@dataclass(frozen=True)
class LightPalette(Palette):
    """Light variant generated by flipping surface/text ramps only."""
    bg_root: str = "#F4F6FA"
    bg_surface: str = "#FFFFFF"
    bg_raised: str = "#EDF0F5"
    bg_input: str = "#E7EBF1"
    bg_overlay: str = "#FFFFFF"
    border_subtle: str = "#D6DBE3"
    border_strong: str = "#B9C2CF"
    divider: str = "#E3E7EE"
    text_primary: str = "#141A22"
    text_secondary: str = "#4A5563"
    text_muted: str = "#8A94A3"
    text_inverse: str = "#FFFFFF"
    dot_stale: str = "#B07E14"


PALETTE_LIGHT = LightPalette()


# ------------------------------------------------------------ radii/border
RADIUS_SM = 4
RADIUS_MD = 8
RADIUS_LG = 12
RADIUS_PILL = 999
BORDER_W = 1
BORDER_W_FOCUS = 2


# --------------------------------------------------------------- elevation
#: subtle shadow levels as (blur_radius, y_offset, rgba_string)
ELEVATION_0 = (0, 0, "transparent")
ELEVATION_1 = (12, 2, "rgba(0,0,0,0.35)")
ELEVATION_2 = (24, 6, "rgba(0,0,0,0.45)")
ELEVATION_3 = (40, 12, "rgba(0,0,0,0.55)")


# ------------------------------------------------------------ control sizes
CONTROL_H_SM = 28
CONTROL_H_MD = 34
CONTROL_H_LG = 42
ICON_SM = 16
ICON_MD = 20
ICON_LG = 28
TILE_MIN = 96            # champion grid minimum tile width
TILE_MAX = 160


# ---------------------------------------------------------------- animation
ANIM_FAST_MS = 120
ANIM_NORMAL_MS = 200
ANIM_SLOW_MS = 320


# -------------------------------------------------------- compact mode sizing
COMPACT_SIZES = {
    "small": (200, 260),
    "medium": (240, 320),
    "large": (280, 360),
}

MAIN_WINDOW_MIN = (980, 640)
